/*
 * Renders src/core/unicode-tables.js from the Unicode data files in
 * tools/unicode/data/, which are Unicode 17.0.0's, unmodified.
 * tools/unicode/generate.mjs writes it; the gate compares against it.
 *
 * Each table is a set of code points, written as ranges: the gap from the end
 * of the previous range and the range's length, in base 36. Short to paste,
 * and decoded once when the artifact loads.
 */
import { readFile } from "node:fs/promises";
import path from "node:path";
import { root } from "../repository.mjs";
import { encodeRanges } from "./ranges.mjs";

const DATA = path.join(root, "tools/unicode/data");
const TARGET = path.join(root, "src/core/unicode-tables.js");
const VERSION = "17.0.0";
const LINE_WIDTH = 180;
const HEX = 16;

// The data lines of a Unicode file, as fields, without comments.
async function records(file) {
    const text = await readFile(path.join(DATA, file), "utf8");

    return text.split("\n")
        .map((line) => line.split("#")[0].trim())
        .filter((line) => line !== "")
        .map((line) => line.split(";").map((field) => field.trim()));
}

function points(field) {
    const [first, last = first] = field.split("..").map((hex) => Number.parseInt(hex, HEX));

    return { first, last };
}

// Code point ranges whose property value is one of `values`.
async function propertyRanges(file, values) {
    return (await records(file))
        .filter(([, value]) => values.includes(value))
        .map(([field]) => points(field));
}

// Bases that a selector follows in a sequences file, by selector.
async function sequenceBases(file) {
    const bases = new Map();

    for (const [sequence] of await records(file)) {
        const [base, selector] = sequence.split(" ").map((hex) => Number.parseInt(hex, HEX));

        bases.set(selector, [...bases.get(selector) ?? [], { first: base, last: base }]);
    }

    return bases;
}

function chunked(text) {
    const chunks = [];

    for (let start = 0; start < text.length; start += LINE_WIDTH) {
        chunks.push(`        ${JSON.stringify(text.slice(start, start + LINE_WIDTH))}`);
    }

    return `[\n${chunks.join(",\n")}\n    ].join("")`;
}

async function tables() {
    const joining = "DerivedJoiningType.txt";
    const [emoji, standardized] = [await sequenceBases("emoji-variation-sequences.txt"), await sequenceBases("StandardizedVariants.txt")];
    const entries = [
        ["JOINING_LEFT", await propertyRanges(joining, ["L", "D"])],
        ["JOINING_RIGHT", await propertyRanges(joining, ["R", "D"])],
        ["TRANSPARENT", await propertyRanges(joining, ["T"])],
        ["VIRAMA", await propertyRanges("DerivedCombiningClass.txt", ["9"])]
    ];

    const selectors = new Map(emoji);

    for (const [selector, bases] of standardized) {
        selectors.set(selector, [...selectors.get(selector) ?? [], ...bases]);
    }

    const bySelector = [...selectors].sort(([left], [right]) => left - right)
        .map(([selector, bases]) => [selector.toString(HEX).toUpperCase(), bases]);

    return { entries, bySelector };
}

function header(license) {
    return `"use strict";\n\n/*\n * Generated by tools/unicode/generate.mjs from the Unicode ${VERSION} data\n` +
        " * files in tools/unicode/data/. Do not edit; regenerate. Each value is a set\n" +
        " * of code points, encoded as src/core/unicode-sets.js decodes it.\n *\n" +
        ` * These tables are derived from Unicode data files, under this notice:\n *\n${
            license.trimEnd().split("\n").map((line) => ` *${line === "" ? "" : ` ${line}`}`).join("\n")}\n */\n\n`;
}

export async function renderTables() {
    const license = await readFile(path.join(DATA, "LICENSE"), "utf8");
    const { entries, bySelector } = await tables();
    const body = entries.map(([name, ranges]) => `    ${name}: ${chunked(encodeRanges(ranges))}`).join(",\n");
    const selectors = bySelector.map(([selector, ranges]) => `        "${selector}": ${chunked(encodeRanges(ranges)).replaceAll("\n    ", "\n        ")}`)
        .join(",\n");

    return `${header(license)}module.exports = {\n    UNICODE_VERSION: "${VERSION}",\n${body},\n` +
        `    // Bases each variation selector is defined after, keyed by the selector in hex.\n` +
        `    SELECTORS: {\n${selectors}\n    }\n};\n`;
}

export { TARGET, VERSION };
