"use strict";

/*
 * Generated by tools/unicode/generate.mjs from the Unicode 17.0.0 data
 * files in tools/unicode/data/. Do not edit; regenerate. Each value is a set
 * of code points, encoded as src/core/unicode-sets.js decodes it.
 *
 * These tables are derived from Unicode data files, under this notice:
 *
 * UNICODE LICENSE V3
 *
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright © 1991-2026 Unicode, Inc.
 *
 * NOTICE TO USER: Carefully read the following legal agreement. BY
 * DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
 * SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
 * TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
 * DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of data files and any associated documentation (the "Data Files") or
 * software and any associated documentation (the "Software") to deal in the
 * Data Files or Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or sell
 * copies of the Data Files or Software, and to permit persons to whom the
 * Data Files or Software are furnished to do so, provided that either (a)
 * this copyright and permission notice appear with all copies of the Data
 * Files or Software, or (b) this copyright and permission notice appear in
 * associated Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
 * THIRD PARTY RIGHTS.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
 * BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
 * OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
 * FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder shall
 * not be used in advertising or otherwise to promote the sale, use or other
 * dealings in these Data Files or Software without prior written
 * authorization of the copyright holder.
 */

module.exports = {
    UNICODE_VERSION: "17.0.0",
    JOINING_LEFT: [
        "17k,5,1,1.4,4.c,1.6,1.1,z.1,8.f,i.11,1.1,9,1,1.1,14.2,2,i.2,5.3,1.8,1,1,1.1,v.a,3.e,2.3,1,2.2,2.5,22.w,2e.4,2,1.9,1,a,1.3,2,t,2.4,1,g.9,5.1,2.5,1.e,30e,o.2g,e.x,1,sd1.1e,jf1.4,8,5.",
        "9,1.2,a.3,41,1,3.2,1.1,1,2,s.1,9d.x,1,bj.1,1.1,2w.2,1.g,c.2,s.3,2.b,1a,1.1,4,2.1,1.1,1,2,5.1,16wk.1v"
    ].join(""),
    JOINING_RIGHT: [
        "17k,1.t,1.9,z.1,1.2,1.2m,1,o.1,a.2,2,g,1.t,t.1e,22.w,2d.o,7,1.3,1.3,5.i,3,2.6,g.c,1.q,30e,o.2g,e.x,1,sd1.1d,jf2.5,1,1.1,3.8,1.9,2,6.4,40.h,n.5,9e.y,bi.2,1.1,2w.k,c.3,r.h,1a,1.4,1.7",
        ",1.3,4.1,16wl.1v"
    ].join(""),
    TRANSPARENT: [
        "4t,gi.33,7n.6,7b.18,1,1.1,1.1,1,20.a,1,1a.k,g,2t.6,2.5,2.1,1.3,x,1,u.q,2j.a,1m.8,9,o.3,1.8,1.2,1.4,17.2,1n.8,16.n,1.v,1j,1,4.7,4,3.6,a.1,t,1m,4.3,8,k.1,q,2.1,1l,4.1,4.1,2.2,3,u.1,3",
        ",b.1,1l,4.4,1.1,4,k.1,m.5,1,1m,2,1.3,8,7.1,b.1,u,1p,c,1e,3,1j,1.2,5.2,1.3,7.1,b.1,t,1m,2,6,5.1,k.1,s.1,1l.1,4.3,8,k.1,t,20,7.2,1,2i,2.6,c.7,2q,2.8,b.6,21.1,r,1,1,1j.d,1.4,1.1,5.a,1",
        ".z,9,2u.3,1.5,1.1,2.1,p.1,4.2,g.3,d,2.1,6,f,jj.2,qa.2,t.1,u.1,u.1,1s.1,1.6,8,2.a,9,19.2,1,39.1,y,3a.2,4.1,9,6.2,63.1,2,1m,1.6,1,1,2.7,6.9,2,1c.19,2.b,k.3,1c,1.4,1,5,14.8,c.1,w.3,2.",
        "1,1.2,1k,1.1,3,1.2,1m.7,2.1,48.2,1.c,1.6,4,6,3.1,5i.1r,ej,2.1,q.4,1d.4,5.5,2o.w,2da.2,3x,2o.v,fe.3,2z.1,n9w.3,1.9,w.1,28.1,7k,3,4,p.1,5,47.1,q.h,d,12.7,p.a,1a.2,1c,2.3,2.1,13,1v.5,",
        "2.1,2.1,c,8,1b,1f,1.2,2.1,5.1,1,16.1,8,6m,2,4,fn4,kh.f,g.f,5r,6x.2,e9,6a,45.4,1ae.2,1.1,5.3,14.2,4,4l.1,fx.3,1t.4,8t.1,25.5,1y.a,1d.3,3f,1i.e,15,2.1,a.2,1d.3,2.1,7,1p.2,10.4,1.7,1q",
        ",c.1,1g.8,a.3,2,2n.2,2,1.1,6,2,4d,3.7,l.1,1l.1,3,11.6,3.4,1y.5,d,1,1,e.1,2d.7,2.2,1,n,2c.5,1,4.1,1.1,6m.3,6.1,1.1,r.1,2d.7,2,1.1,2y,1,2.5,1,2t,1,2.3,1.4,77.8,1.1,74.1,1,4,40.3,2.1,",
        "4,w.9,14.5,2.3,8,9.5,2.2,1a.c,1.1,5i,1.2,1,5l.6,1.5,1,2a.l,2.6,1.1,1.1,3e.5,3,1.1,1.6,1,20.1,3,1,9n.1,b.1,1g.4,5,1,n,445.g,6.e,8ug.b,3.2,1xc.4,1n.6,t4,1r.3,29,f5k.1,1.3,3mk.19,2.m,",
        "f4.2,9.f,2.6,u.3,44.2,1iz.1i,4.1d,8,e,m.4,1.e,11s.6,1.g,2.6,1.1,1.4,2s,4g.6,af,1p.3,e4.3,72.1,6r,2,7.1,5,d6.6,31.7,gzat,u.2n,3k.6n"
    ].join(""),
    VIRAMA: [
        "1u5,3j,3j,3j,3j,3j,3j,3j,31.1,g,3g,33,3j,5l,50.1,1cp.1,u,4d,i5,6b,2t.1,1y.1,3gr,o7a,11,47,3y,30,8l,6u,imp,16u,15,e,1l,3d.1,3v,38,50,2q,3k.2,35,3j,70,3j,3a,38,7h,77.1,4h,2b,i,29,bp,",
        "78.1,29,bt.1,d0s"
    ].join(""),
    // Bases each variation selector is defined after, keyed by the selector in hex.
    SELECTORS: {
        "180B": [
            "4rk.6,1,1,1.1,2,1.1,1.1,1,b.5,3.1,e.1,1,2,4.1,5,3.1,1,9.1,5.1,1"
        ].join(""),
        "180C": [
            "4rk,4.1,1,3.1,2,5,g,m,9,a.1,i"
        ].join(""),
        "180D": [
            "4rs,3.1,1x.1,i"
        ].join(""),
        "FE00": [
            "1c,34f,1,1,b.1,3,3.1,1.1,4,e,1v,2,1,5,32v.1,2.1,6l,4,1,8,g,3.1,1,5t,z.1,1p.1,8.1,m.1,7.2,1,4,1p.1,1cr,3o.1,2n.1,d.1,t.1,110.1,wr,q,1,z,1h,d4,d,3o,4t,1e,p,22,r,1k,t,6r,1p,3b,z,g,1b,",
            "2b,3e,1h,6c,2q,7p,b,2q,68,b,f,w,c,27,24,23,5u,10,3c,2o,1e,10,3f,3,1d,2n,5b,1d,3,9,2z,x,1n,3s,8,jx,28,3r,7,1n,3k,4a,73,u,a,2l,52,o,b,5.1,3,3,1s,3,13,h,b,n,3f,v,5,4,y,c,3,1u,14,26,u,",
            "1h,a,c,2g,4,7,6,f,2.2,3,9,8,c,4,2,1,c,7,8,1,h,2,f,1,m,d,3,f,h,g.1,a,17,4,h,h,7,f,j,1,8,b,5,g,4,a.1,g,13,9,7,8,o,1,7,1,1v,6,k,5,5,5,k,8,d,q,9,5,v,1h,3,q,1k,p,1u,1,d,w,2,h,3,d,7,c,1,",
            "v,z,22,m,b,3o,s.1,37,1u,11,o,z.1,d,p,3,21,3,6,10,6,e,3,4,e,j,7,x,3,8,2,d,g,2s,j,1a,b,1m,3,26,2a,v,l,1y,1p,k,e,6,4,b,6,r,s,w,1,1.1,8,u,1e,2g,15,c,q,2,d,1h,7,12.1,q,16,k,17,a,1d,9,2,",
            "2,i.1,7.1,5,i,h,5,t,1c,e,6,1,v,e,e,3,v,9,t,3,o,9,2g,b,i,1e,g,8,12,1n,3,3,1,h,7,h,j,1,j,a,2,17,j,3,9,f,a,i,5,14,2b,n,5,3.1,13,1,1q,i,n,i,7,s,8,q.1,u,1j,5,1b,m,d,6,r,2,12,3u,6,l,b,w,",
            "17,s.1,1b,1h,16,j,8,a,n,h,19,3,7,m,3,5,18,4,2,7,s,9,h,2j,6,s,7,1e,1a,3,8,p,2z,19,2o,1y,n,g,44,16,7,14,s,1e,t,4,1,11,e,b.1,42,o,w,1i,c.1,n,1c,4,2,l,9,2,13.1,c.1,c,1x,e,f,e,w,k,1q,19",
            ",t,c,3,5,9,1f,i.1,22,2f,10,i,s,2,q,g,11,6,5,r,j,q,g,2z,3,10,19,1d,1,1r,a,c,2,9,q,h,t,k,p,g,1n,19,22,4,c,3,p,c,17,13,2,o,10,k,c,7,j,3,e,1d,1n,t,m,2,q,b,a,35,19,c,1,y,12,2o,g,b,c,c,s",
            ".1,w,9,1s,r,4m,s,w,4,1k,1,1a,1a,h,1,9.1,6,5,6.1,6,p,d.2,u,r,w,1c,z,9,4,1d,1b,p,y,1d,4f,5,2,38,x,q,m,17,j,3,c,3.1,n,f,h,c,17,7,1o,t,8,18,d,6,19,9,3,6w,1f,6.1,a,f,4,y,1o,6,3,1s,p,e.1",
            ",d,c,x,4,28,1m,49,f,4,j,2,j,2e,9,h,5,b,j,1,9,13.1,1i,5,i,r.1,f,21,f,b.1,1,f,a,7,1,23,b,d,46,2,1,8,p,25,2w,18,b,b,q,h,g,b,a,1,u,w,1k,17,p,1u,d,c,1f,12,v,t,18,j,2,2m,c,7,6,2,m,1,l,1c",
            ",y,x,4,a,7d,9,k,b,6,3,m,a,5,2,1j,u,13,9,59,c,2d,l.1,5,a,1g,i,2j,1w,e,z.1,61,9,29,3,d,2,12,1n,h,5,30,k,1l,9,i,4,1l,f,i,b,j,9,26,1a,q,n,2,1,2q,3,1p,5,2i.1,17,1x,4u,r,ad,x,9,3a,s,1,13",
            ",2,3,9,s,j.1,a,u.1,i.1,17,e,l,d,3o,4,u,b,c,g,h,y,3n,c,c,17.1,3h,q,1a,c,2z,4n,2k,5s,m,4l,2x,24,1x,z,2o,n,7,r,i,16,4,6,9,6,10,7,21.1,d,1q1,5,1.2,7,dz.6,4.1,2,a,gp2,a,1,1,9.1,3,2at.1,",
            "f.1,9,7fz,3h,c,4,5,h,2u,g,6.1,h,k,o.1,3k,3,5,6,t,w,g,a,v,j,6,p,1m.1,w.1,1k,g.1,1,6,3,2.1,v,2.1,8,v.3,1i9.2,p3,tgp,1.1,2,2.1,2.3,1.7,8rw,s9,8,11,6m,cp,61,99,8m,1vk,cj,1t,kd,9b,du,60",
            ",1,po,r,b5,pu,a7,5,jl,6c,t4,j1,4m,1f,8,12,h,47,fp,eb,dh,30,ch,2p,c2,3w,1b,k4,3u,58,gs,8c,66,td,2j,lq,m,3v,4t.1,11,p,7p,cz,eg,37,16,ja,8a,77,5w,27,j9,gj,25,u,41,2s,bf,20,3o,e6,d,p2,",
            "6x,4e,45,cg,3o,80,l3,ik,g6,53,n5,fe,2j,1b6,q,8w,y3,ak,r1,49,1m,dr,3v,7z,12x,13x,1i,7c,3m,74,h9"
        ].join(""),
        "FE01": [
            "6c8.1,2.1,6l,4,1,8,g,3.1,1,2x9.1,2ai,m2,ao,31w,8o,2t,2v,29,5b,1,q,l,s,1l,19,ec,k,3,2w,gj,kj,4o,3q,gr,2f,a9,53,1,1r,2r,3,ns,84,s,3p,3,a1,ak,c7,au,1h,9f,2e,6z,9b,5i,6s,2k,6h,72,9l,15",
            ",16,16,8x,1r,3t,1k,4w,an,fn,eo,e3,3b,2z,a9,ec,7w,f0,7n,1u,a,5,2,1j,28,al,fj,73,1be,36,4o,b,1b,k6,w9,iuc,a,1,b.1,3,9rn,4e,6,25,15,1o,9.2,2k,13,b,o,2r,9.2,6,5.1,e,52,1c,26d,no,svb,1.",
            "1,2,2.1,2.3,1.7,fi3,ayd"
        ].join(""),
        "FE02": [
            "6c8.1,2.1,a5d,1nr,146,2r,10k,kq,c7,au,3aq,eo,4qt,1hs,sqi,x,21,s,p,1f,13,2s,14,1u,1,e,4,4.1,c.4,7,4,f,o,m,h,9,7,15.1,e,r,1,1n,i,1,2th"
        ].join(""),
        "FE03": [
            "1o2a,4l,1,2c,v,9,22,n.1,1,h,15,15,40,4h,68"
        ].join(""),
        "FE04": [
            "1oah,k3"
        ].join(""),
        "FE05": [
            "1oah,3ei"
        ].join(""),
        "FE06": [
            "1oa7,9,22,2e,i,m,4e,1w,1t,c,1j.1,4n,2u2"
        ].join(""),
        "FE0E": [
            "z,6,5.9,33,4,68d,c,60,m,2i.5,f.1,a7.1,c,4m,p.a,4.2,5j,6f.1,a,9,1m.3,1.4,9,2,2.1,2,4,2,1.1,2,3,3.1,8.2,5,1,5.b,b.1,2,1.1,1,i,2.1,i.5,1,1.1,3.1,5,2.1,4.1,b.1,5.1,2,5.1,1,1.1,k.1,5.5,",
            "1.3,2,4,2,2.5,1,2,1,1,6,3,6,a.1,f,2,4,1,4.2,1,b.1,1c.2,9,e,e,ac.1,cv.2,j.1,1f,4,yi,c,gp,1,2fze,a3.1,c.1,3m,n,k,7,5x.2,5,6,4,2.8,9,1t,4,l,2.1,1.2,2.1,7,4.2,j,1,1,3.4,5.c,c,5,1,1,g,c",
            ",9,6,o,1.1,3.3,3.1,4,m,i,11,c,2,7,3,b,e,4,4.2,3.3,9,1.2,1,a,4,4.1,1h.1,5.n,7.1,2.6,d,2.3,2,k,2,8.1,9,5.2,c.2,8.2,2,1,4,6,3,6,l,3a,5,3,2,3,k,4,6.1,1,e,1.2,g.5,3,6,2"
        ].join(""),
        "FE0F": [
            "z,6,5.9,33,4,68d,c,60,m,2i.5,f.1,a7.1,c,4m,p.a,4.2,5j,6f.1,a,9,1m.3,1.4,9,2,2.1,2,4,2,1.1,2,3,3.1,8.2,5,1,5.b,b.1,2,1.1,1,i,2.1,i.5,1,1.1,3.1,5,2.1,4.1,b.1,5.1,2,5.1,1,1.1,k.1,5.5,",
            "1.3,2,4,2,2.5,1,2,1,1,6,3,6,a.1,f,2,4,1,4.2,1,b.1,1c.2,9,e,e,ac.1,cv.2,j.1,1f,4,yi,c,gp,1,2fze,a3.1,c.1,3m,n,k,7,5x.2,5,6,4,2.8,9,1t,4,l,2.1,1.2,2.1,7,4.2,j,1,1,3.4,5.c,c,5,1,1,g,c",
            ",9,6,o,1.1,3.3,3.1,4,m,i,11,c,2,7,3,b,e,4,4.2,3.3,9,1.2,1,a,4,4.1,1h.1,5.n,7.1,2.6,d,2.3,2,k,2,8.1,9,5.2,c.2,8.2,2,1,4,6,3,6,l,3a,5,3,2,3,k,4,6.1,1,e,1.2,g.5,3,6,2"
        ].join("")
    }
};
