"use strict";

/*
 * The Unicode tables: generated the same way every time, and each one exactly
 * the set its source file defines, code point by code point.
 */

const assert = require("node:assert/strict");
const test = require("node:test");
const fs = require("node:fs");
const path = require("node:path");
const sets = require("../../../src/core/unicode-sets.js");

const DATA = path.resolve(__dirname, "../../../tools/unicode/data");
const HEX = 16;

// The code points a file gives each value, from its data lines alone.
function fromFile(file, keep) {
    const found = new Set();

    for (const raw of fs.readFileSync(path.join(DATA, file), "utf8").split("\n")) {
        const fields = raw.split("#")[0].split(";").map((field) => field.trim());

        if (fields[0] !== "" && keep(fields)) {
            const [first, last = first] = fields[0].split("..").map((hex) => Number.parseInt(hex, HEX));

            for (let point = first; point <= last; point += 1) {
                found.add(point);
            }
        }
    }

    return found;
}

function assertSame(expected, ask, label) {
    let checked = 0;

    for (let point = 0; point <= 0x10FFFF; point += 1) {
        assert.equal(ask(point), expected.has(point), `${label}: U+${point.toString(HEX)}`);
        checked += 1;
    }

    assert.ok(checked > 0);
}

test("the joining tables are DerivedJoiningType's", () => {
    const left = fromFile("DerivedJoiningType.txt", ([, value]) => value === "L" || value === "D");
    const right = fromFile("DerivedJoiningType.txt", ([, value]) => value === "R" || value === "D");
    const transparent = fromFile("DerivedJoiningType.txt", ([, value]) => value === "T");

    assertSame(left, sets.joinsLeft, "left-joining");
    assertSame(right, sets.joinsRight, "right-joining");
    assertSame(transparent, sets.isTransparent, "transparent");
});

test("the viramas are DerivedCombiningClass's class 9", () => {
    assertSame(fromFile("DerivedCombiningClass.txt", ([, value]) => value === "9"), sets.isVirama, "virama");
});

test("every defined variation sequence, and no other, is known", () => {
    for (const file of ["emoji-variation-sequences.txt", "StandardizedVariants.txt"]) {
        for (const raw of fs.readFileSync(path.join(DATA, file), "utf8").split("\n")) {
            const sequence = raw.split("#")[0].split(";")[0].trim();

            if (sequence !== "") {
                const [base, selector] = sequence.split(" ").map((hex) => Number.parseInt(hex, HEX));

                assert.equal(sets.isDefinedVariation(base, selector), true, `${file}: ${sequence}`);
                assert.equal(sets.isDefinedVariation(base, 0xFE0D), false, "a selector with no sequences");
            }
        }
    }

    assert.equal(sets.isDefinedVariation(0x61, 0xFE0F), false);
    assert.equal(sets.isDefinedVariation(0x628, 0xFE00), false);
});

test("the tables are generated the same way every time, with the Unicode notice", async () => {
    const { renderTables } = await import("../../../tools/unicode/tables.mjs");
    const first = await renderTables();

    assert.equal(await renderTables(), first);
    assert.match(first, /^"use strict";\n\n\/\*\n \* Generated by tools\/unicode\/generate\.mjs/u);
    assert.match(first, /UNICODE LICENSE V3/u, "the Unicode notice travels with the tables");
});

test("the encoder merges overlapping and adjacent ranges, in order", async () => {
    const { encodeRanges, normalise } = await import("../../../tools/unicode/ranges.mjs");

    assert.deepEqual(normalise([{ first: 5, last: 6 }, { first: 1, last: 2 }, { first: 3, last: 3 }, { first: 6, last: 9 }]),
        [{ first: 1, last: 3 }, { first: 5, last: 9 }]);
    assert.equal(encodeRanges([{ first: 10, last: 12 }, { first: 16, last: 16 }]), "a.2,3");
    assert.equal(encodeRanges([]), "");
});
